# Imagen base de python
FROM python:3.12.7-alpine3.20

# Establecer directorio de trabajo
WORKDIR /usr/src/app/

# Instalar dependencias
RUN apk update && \
    apk add --no-cache gcc musl-dev libffi-dev postgresql-dev && \
    pip install --upgrade pip

# Copiar requirements.txt
COPY ./requirements.txt ./
# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar archivos de la aplicación
COPY . .